export const ROUTE_PATHS = {
  ADMIN_HOME: '/admin',
  CLIENT_HOME: '/client',
  SIGN_UP: '/sign-up',
  SIGN_IN: '/sign-in',
  FORGOT_PASSWORD: '/forgot-password',
  RECOVERY_PASSWORD: '/recovery-password',
  WORK_FLOWS  : '/work-flows',
  WORK_FLOWS_CREATE  : '/work-flows-create',
  WORK_FLOWS_DETAIL  : '/work-flows/:id',
  NODES: '/nodes',
  KINDS: '/kinds',
  TYPES: '/types',
  ELEMENTS: '/elements',
}
